services:
    mg8c40oowo80o08o0gsw0gwc-082624592653:
        image: 'mg8c40oowo80o08o0gsw0gwc:3692de12e493ff0bb343810c872bac002c86f956'
        container_name: mg8c40oowo80o08o0gsw0gwc-082624592653
        restart: unless-stopped
        expose:
            - '3000'
            - '8000'
        networks:
            coolify:
                aliases:
                    - mg8c40oowo80o08o0gsw0gwc-082624592653
        mem_limit: '0'
        memswap_limit: '0'
        mem_swappiness: 60
        mem_reservation: '0'
        cpus: 0.0
        cpu_shares: 1024
        env_file:
            - .env
        healthcheck:
            test:
                - CMD-SHELL
                - 'curl -s -X GET -f http://localhost:3000/ > /dev/null || wget -q -O- http://localhost:3000/ > /dev/null || exit 1'
            interval: 30s
            timeout: 10s
            retries: 5
            start_period: 5s
        labels:
            - traefik.enable=true
            - traefik.http.middlewares.gzip.compress=true
            - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
            - traefik.http.middlewares.websocket-upgrade.headers.customrequestheaders.Connection=upgrade
            - traefik.http.middlewares.websocket-upgrade.headers.customrequestheaders.Upgrade=websocket
            - traefik.http.routers.http-0-mg8c40oowo80o08o0gsw0gwc.entryPoints=http
            - traefik.http.routers.http-0-mg8c40oowo80o08o0gsw0gwc.middlewares=redirect-to-https
            - 'traefik.http.routers.http-0-mg8c40oowo80o08o0gsw0gwc.rule=Host(`www.jackcwf.com`) && PathPrefix(`/`)'
            - traefik.http.routers.http-0-mg8c40oowo80o08o0gsw0gwc.service=http-0-mg8c40oowo80o08o0gsw0gwc
            - traefik.http.routers.https-0-mg8c40oowo80o08o0gsw0gwc.entryPoints=https
            - traefik.http.routers.https-0-mg8c40oowo80o08o0gsw0gwc.middlewares=websocket-upgrade,gzip
            - 'traefik.http.routers.https-0-mg8c40oowo80o08o0gsw0gwc.rule=Host(`www.jackcwf.com`) && PathPrefix(`/`)'
            - traefik.http.routers.https-0-mg8c40oowo80o08o0gsw0gwc.service=https-0-mg8c40oowo80o08o0gsw0gwc
            - traefik.http.routers.https-0-mg8c40oowo80o08o0gsw0gwc.tls.certresolver=letsencrypt
            - traefik.http.routers.https-0-mg8c40oowo80o08o0gsw0gwc.tls=true
            - traefik.http.services.http-0-mg8c40oowo80o08o0gsw0gwc.loadbalancer.server.port=3000
            - traefik.http.services.https-0-mg8c40oowo80o08o0gsw0gwc.loadbalancer.server.port=3000
            - traefik.http.routers.https-websocket-mg8c40oowo80o08o0gsw0gwc.entryPoints=https
            - 'traefik.http.routers.https-websocket-mg8c40oowo80o08o0gsw0gwc.rule=Host(`www.jackcwf.com`) && PathPrefix(`/_event`)'
            - traefik.http.routers.https-websocket-mg8c40oowo80o08o0gsw0gwc.service=https-websocket-mg8c40oowo80o08o0gsw0gwc
            - traefik.http.routers.https-websocket-mg8c40oowo80o08o0gsw0gwc.middlewares=websocket-upgrade@docker
            - traefik.http.routers.https-websocket-mg8c40oowo80o08o0gsw0gwc.tls=true
            - traefik.http.routers.https-websocket-mg8c40oowo80o08o0gsw0gwc.tls.certresolver=letsencrypt
            - traefik.http.services.https-websocket-mg8c40oowo80o08o0gsw0gwc.loadbalancer.server.port=8000
            - 'caddy_0.encode=zstd gzip'
            - 'caddy_0.handle_path.0_reverse_proxy={{upstreams 3000}}'
            - 'caddy_0.handle_path=/*'
            - caddy_0.header=-Server
            - 'caddy_0.try_files={path} /index.html /index.php'
            - 'caddy_0=https://www.jackcwf.com'
            - caddy_ingress_network=coolify
            - coolify.managed=true
            - coolify.version=4.0.0-beta.434
            - coolify.applicationId=3
            - coolify.type=application
            - coolify.name=mg8c40oowo80o08o0gsw0gwc
            - coolify.resourceName=datalablifejackcwfmain-t8ksc8so4o88c084ow4koog8
            - coolify.projectName=my-first-project
            - coolify.serviceName=datalablifejackcwfmain-t8ksc8so4o88c084ow4koog8
            - coolify.environmentName=production
            - coolify.pullRequestId=0
networks:
    coolify:
        external: true
        name: coolify
        attachable: true
